on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: '^1.17.3'
    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
    - name: Install JS Deps
      run: pnpm install --frozen-lockfile
    - name: Run Test
      run: make test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
      with:
        file: ./coverage/cover.out
        github-token: ${{ secrets.GITHUB_TOKEN }}
